### ISSUE TITLE
Docker CMR doesn't work (boot2docker)

### ISSUE THREAD

**Issue by cbonami** [inspectIT/inspectIT#18]
Hi

I'm using OsX Yosemite, docker and boot2docker/VirtualBox (the only way to run docker images on OSX). I just installed the docker image via the command (install guide):

docker run -d --name inspectIT-CMR -p 8182:8182 -p 9070:9070 inspectit/cmr

After that I tried to connect the InspectIt client to the docker server (dockerhost:8182). Didn't work.

So I ssh-ed into the container and checked the logs:

2015-08-11 11:42:06,845: 332    [           main] INFO  info.novatec.inspectit.cmr.CMR - Central Measurement Repository is starting up!
2015-08-11 11:42:06,848: 335    [           main] INFO  info.novatec.inspectit.cmr.CMR - ==============================================
2015-08-11 11:42:06,848: 335    [           main] INFO  info.novatec.inspectit.cmr.CMR - Initializing Spring...
2015-08-11 11:42:08,081: 1568   [           main] INFO  t.cmr.property.PropertyManager - |-Loading the default CMR configuration
2015-08-11 11:42:08,203: 1690   [           main] INFO  t.cmr.property.PropertyManager - |-No CMR Configuration updates found, continuing to use default configuration
2015-08-11 11:42:08,219: 1706   [           main] INFO  t.cmr.property.PropertyManager - |-CMR Configuration verified with no errors
2015-08-11 11:42:08,241: 1728   [           main] INFO  ring.exporter.RemotingExporter - |-RemoteExporter: Processing Beans for remote export
2015-08-11 11:42:08,745: 2232   [           main] INFO  mr.cache.impl.BufferProperties - |-Buffer properties initialized with following values:
2015-08-11 11:42:08,745: 2232   [           main] INFO  mr.cache.impl.BufferProperties - ||-Eviction occupancy percentage: 95%
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Eviction fragment size percentage: 5%
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Indexing tree cleaning threads: 1
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Indexing waiting time: 500 ms
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min old generation occupancy percentage active till: 402,653,184 bytes
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max old generation occupancy percentage active from: 2,147,483,648 bytes
2015-08-11 11:42:08,746: 2233   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min old generation occupancy percentage: 50%
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max old generation occupancy percentage: 65%
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion: 10%
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion: 1%
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion active from buffer occupancy: 75%
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion active till buffer occupancy: 35 %
2015-08-11 11:42:08,747: 2234   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion active till buffer size: 209,715,200 bytes
2015-08-11 11:42:08,748: 2235   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion active from buffer size: 1,073,741,824 bytes
2015-08-11 11:42:08,835: 2322   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Using buffer with maximum size 598,817,536 bytes...
2015-08-11 11:42:08,835: 2322   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Indexing tree maintenance on 44,911,316 bytes added/removed...
2015-08-11 11:42:08,836: 2323   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Using object expansion rate of 5.81%
2015-08-11 11:42:14,281: 7768   [           main] INFO  mr.service.ServerStatusService - |-Server Status Service active...
2015-08-11 11:42:14,320: 7807   [           main] INFO  izer.schema.ClassSchemaManager - ||-Class Schema Manager started..
2015-08-11 11:42:14,735: 8222   [           main] INFO  ectit.cmr.util.ShutdownService - |-Shutdown Service active...
2015-08-11 11:42:14,740: 8227   [           main] INFO  r.service.CmrManagementService - |-CMR Management Service active...
2015-08-11 11:42:14,748: 8235   [           main] INFO  mr.service.AgentStorageService - |-Agent Storage Service active...
2015-08-11 11:42:14,765: 8252   [           main] INFO  ervice.GlobalDataAccessService - |-Global Data Access Service active...
2015-08-11 11:42:14,778: 8265   [           main] INFO  ice.ExceptionDataAccessService - |-Exception Sensor Data Access Service active...
2015-08-11 11:42:14,789: 8276   [           main] INFO  ice.HttpTimerDataAccessService - |-Http Timer Data Access Service active...
2015-08-11 11:42:14,799: 8286   [           main] INFO  ce.InvocationDataAccessService - |-Invocation Data Access Service active...
2015-08-11 11:42:14,813: 8300   [           main] INFO  mr.service.RegistrationService - |-Registration Service active...
2015-08-11 11:42:14,822: 8309   [           main] INFO  r.service.SqlDataAccessService - |-SQL Data Access Service active...
2015-08-11 11:42:14,839: 8326   [           main] INFO  tit.cmr.service.StorageService - |-Storage Service active...
2015-08-11 11:42:15,480: 8967   [           main] INFO                               / - Initializing Spring FrameworkServlet 'springDispatcherServletExporter'
2015-08-11 11:42:15,834: 9321   [           main] INFO  bApplicationContextInitializer - | Jetty Web Application Context started!
2015-08-11 11:42:15,882: 9369   [           main] INFO  tor$$EnhancerByCGLIB$$729598ac - |-Kryonet server successfully started and running on port 9070
2015-08-11 11:42:15,901: 9388   [           main] INFO  rter.KryoNetRmiServiceExporter - |-Service info.novatec.inspectit.cmr.service.IAgentStorageService exported and available via kryonet RMI with the ID 2
2015-08-11 11:42:15,903: 9390   [           main] INFO  rter.KryoNetRmiServiceExporter - |-Service info.novatec.inspectit.cmr.service.IRegistrationService exported and available via kryonet RMI with the ID 1
2015-08-11 11:42:15,915: 9402   [           main] INFO  info.novatec.inspectit.cmr.CMR - Spring successfully initialized
2015-08-11 11:42:15,918: 9405   [           main] INFO  info.novatec.inspectit.cmr.CMR - Starting CMR in version 1.6.2.65
2015-08-11 11:42:15,920: 9407   [           main] INFO  info.novatec.inspectit.cmr.CMR - CMR started in 9076.102577 ms
2015-08-11 11:43:21,180: 74667  [      btpool0-3] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:43:40,996: 94483  [      btpool0-3] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:43:42,752: 96239  [      btpool0-0] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:44:42,794: 156281 [      btpool0-4] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:45:42,829: 216316 [      btpool0-2] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:46:42,860: 276347 [      btpool0-5] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:47:42,893: 336380 [      btpool0-3] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:48:42,928: 396415 [      btpool0-4] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]
2015-08-11 11:49:42,956: 456443 [      btpool0-2] ERROR                org.mortbay.log - /remoting/ServerStatusService
java.lang.ClassCastException: info.novatec.inspectit.communication.comparator.HttpTimerDataComparatorEnum cannot be cast to org.springframework.remoting.support.RemoteInvocation
	at info.novatec.inspectit.cmr.spring.exporter.KryoHttpInvokerServiceExporter.readRemoteInvocation(KryoHttpInvokerServiceExporter.java:44) ~[inspectit-cmr.jar:na]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.readRemoteInvocation(HttpInvokerServiceExporter.java:95) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:72) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at org.springframework.web.context.support.HttpRequestHandlerServlet.service(HttpRequestHandlerServlet.java:67) ~[org.springframework.web-3.1.0.RELEASE.jar:3.1.0.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet-3.0.0.v201103241009.jar:na]
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1221) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:78) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:131) ~[jetty-util-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1212) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:399) ~[jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.Server.handle(Server.java:326) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228) [jetty-6.1.26.jar:6.1.26]
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:451) [jetty-util-6.1.26.jar:6.1.26]

**Comment by stefansiegl** [comment]
Hi,

Thank you for your feedback. Will analyze this right away.

Cheers,
Stefan

**Comment by stefansiegl** [comment]
I just tried it on my environment (running Ubuntu, thus no boot-2-docker). Here everything seems fine:

```
stefan@nt-notebook-ssl:~$ sudo docker run -d --name inspectIT-CMR -p 8182:8182 -p 9070:9070 inspectit/cmr
ca4d938e5fa7fdbdabef4683026a2a72ea7ff0e81feab461377c9a42f126e3d1
stefan@nt-notebook-ssl:~$ sudo docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS                                            NAMES
ca4d938e5fa7        inspectit/cmr:latest   "/bin/sh -c '/bin/sh   7 seconds ago       Up 5 seconds        0.0.0.0:8182->8182/tcp, 0.0.0.0:9070->9070/tcp   inspectIT-CMR       
stefan@nt-notebook-ssl:~$ sudo docker logs inspectIT-CMR 
2015-08-11 12:05:28,440: 217    [           main] INFO  info.novatec.inspectit.cmr.CMR - Central Measurement Repository is starting up!
2015-08-11 12:05:28,442: 219    [           main] INFO  info.novatec.inspectit.cmr.CMR - ==============================================
2015-08-11 12:05:28,442: 219    [           main] INFO  info.novatec.inspectit.cmr.CMR - Initializing Spring...
2015-08-11 12:05:29,335: 1112   [           main] INFO  t.cmr.property.PropertyManager - |-Loading the default CMR configuration
2015-08-11 12:05:29,420: 1197   [           main] INFO  t.cmr.property.PropertyManager - |-No CMR Configuration updates found, continuing to use default configuration
2015-08-11 12:05:29,433: 1210   [           main] INFO  t.cmr.property.PropertyManager - |-CMR Configuration verified with no errors
2015-08-11 12:05:29,449: 1226   [           main] INFO  ring.exporter.RemotingExporter - |-RemoteExporter: Processing Beans for remote export
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - |-Buffer properties initialized with following values:
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Eviction occupancy percentage: 95%
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Eviction fragment size percentage: 5%
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Indexing tree cleaning threads: 1
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Indexing waiting time: 500 ms
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min old generation occupancy percentage active till: 402,653,184 bytes
2015-08-11 12:05:29,805: 1582   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max old generation occupancy percentage active from: 2,147,483,648 bytes
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min old generation occupancy percentage: 50%
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max old generation occupancy percentage: 65%
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion: 10%
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion: 1%
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion active from buffer occupancy: 75%
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion active till buffer occupancy: 35 %
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Max object size expansion active till buffer size: 209,715,200 bytes
2015-08-11 12:05:29,806: 1583   [           main] INFO  mr.cache.impl.BufferProperties - ||-Min object size expansion active from buffer size: 1,073,741,824 bytes
2015-08-11 12:05:29,874: 1651   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Using buffer with maximum size 598,817,536 bytes...
2015-08-11 12:05:29,874: 1651   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Indexing tree maintenance on 44,911,316 bytes added/removed...
2015-08-11 12:05:29,874: 1651   [           main] INFO  it.cmr.cache.impl.AtomicBuffer - |-Using object expansion rate of 5.81%
2015-08-11 12:05:32,138: 3915   [           main] INFO  mr.service.ServerStatusService - |-Server Status Service active...
2015-08-11 12:05:32,371: 4148   [           main] INFO  ectit.cmr.util.ShutdownService - |-Shutdown Service active...
2015-08-11 12:05:32,377: 4154   [           main] INFO  r.service.CmrManagementService - |-CMR Management Service active...
2015-08-11 12:05:32,384: 4161   [           main] INFO  mr.service.AgentStorageService - |-Agent Storage Service active...
2015-08-11 12:05:32,402: 4179   [           main] INFO  ervice.GlobalDataAccessService - |-Global Data Access Service active...
2015-08-11 12:05:32,414: 4191   [           main] INFO  ice.ExceptionDataAccessService - |-Exception Sensor Data Access Service active...
2015-08-11 12:05:32,423: 4200   [           main] INFO  ice.HttpTimerDataAccessService - |-Http Timer Data Access Service active...
2015-08-11 12:05:32,432: 4209   [           main] INFO  ce.InvocationDataAccessService - |-Invocation Data Access Service active...
2015-08-11 12:05:32,448: 4225   [           main] INFO  mr.service.RegistrationService - |-Registration Service active...
2015-08-11 12:05:32,456: 4233   [           main] INFO  r.service.SqlDataAccessService - |-SQL Data Access Service active...
2015-08-11 12:05:32,470: 4247   [           main] INFO  tit.cmr.service.StorageService - |-Storage Service active...
2015-08-11 12:05:32,602: 4379   [           main] INFO  izer.schema.ClassSchemaManager - ||-Class Schema Manager started..
2015-08-11 12:05:33,079: 4856   [           main] INFO                               / - Initializing Spring FrameworkServlet 'springDispatcherServletExporter'
2015-08-11 12:05:33,312: 5089   [           main] INFO  bApplicationContextInitializer - | Jetty Web Application Context started!
2015-08-11 12:05:33,409: 5186   [           main] INFO  tor$$EnhancerByCGLIB$$729598ac - |-Kryonet server successfully started and running on port 9070
2015-08-11 12:05:33,425: 5202   [           main] INFO  rter.KryoNetRmiServiceExporter - |-Service info.novatec.inspectit.cmr.service.IAgentStorageService exported and available via kryonet RMI with the ID 2
2015-08-11 12:05:33,427: 5204   [           main] INFO  rter.KryoNetRmiServiceExporter - |-Service info.novatec.inspectit.cmr.service.IRegistrationService exported and available via kryonet RMI with the ID 1
2015-08-11 12:05:33,434: 5211   [           main] INFO  info.novatec.inspectit.cmr.CMR - Spring successfully initialized
2015-08-11 12:05:33,434: 5211   [           main] INFO  info.novatec.inspectit.cmr.CMR - Starting CMR in version 1.6.2.65
2015-08-11 12:05:33,434: 5211   [           main] INFO  info.novatec.inspectit.cmr.CMR - CMR started in 4995.415635 ms
```

We had this error before (https://inspectit-performance.atlassian.net/wiki/display/SAM/Netflix+RSS+Demo+Application?focusedCommentId=9502782#comment-9502782). I will continue checking and get back to you.

Stefan

**Comment by cbonami** [comment]
maybe try on a mac; it shouldn't matter ... but you never know ;)

**Comment by stefansiegl** [comment]
@mariomann has a mac at home. He will test it

**Comment by ivansenic** [comment]
I think this might be related to the versions of the Agent and CMR. I suspect they are not in the same version. I see that the CMR is in version 1.6.2.65, can you check please that the agent is also in the same one?

**Comment by cbonami** [comment]
Well, it's the agent that I downloaded here (http://www.inspectit.eu/download-inspectit/) today. The docker image I also installed today (by running it). When I unpack the zip with the agent, I see it is dated april 2014. A bit old, I thought.

Anyway, outdated agent or not, I should be able to connect to the CMR with my client, not ?
I never succeeded doing that, even after restarting the CMR.

**Comment by ivansenic** [comment]
@stefansiegl  You are just staring the CMR, this also works for the @cbonami .. Try connecting the agent..

**Comment by ivansenic** [comment]
@cbonami  The docker example runs the CMR in version 1.6.2.65, while the download page offers two options:
* 1.5.59 (called stable on the page)
* 1.6.2.65 (called beta)

You should use the beta one to use in with docker: ftp://ntftp.novatec-gmbh.de/inspectit/releases/RELEASE.1.6.2.65/inspectit-agent-sun1.5.zip

**Comment by cbonami** [comment]
Ok, I installed the new agent.
I restarted the docker CMR.
Then when I start my java app (JDK8, tomcat 8), I get this while starting:

2015-08-11 14:27:15,045: [inspectIT] 6834   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/2049051802
2015-08-11 14:27:15,048: [inspectIT] 6837   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1752182275
2015-08-11 14:27:15,053: [inspectIT] 6842   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1541697437
2015-08-11 14:27:15,056: [inspectIT] 6845   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1902430796
2015-08-11 14:27:15,059: [inspectIT] 6848   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1759482496
2015-08-11 14:27:15,063: [inspectIT] 6852   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/305502850
00:05  INFO: Connecting: /192.168.59.103:9070
2015-08-11 14:27:15,066: [inspectIT] 6855   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1647946662
2015-08-11 14:27:15,070: [inspectIT] 6859   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1237740254
2015-08-11 14:27:15,073: [inspectIT] 6862   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/532048323
2015-08-11 14:27:15,076: [inspectIT] 6865   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/322561962
2015-08-11 14:27:15,079: [inspectIT] 6868   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/951221468
2015-08-11 14:27:15,083: [inspectIT] 6872   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1414549197
2015-08-11 14:27:15,087: [inspectIT] 6876   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1958680465
2015-08-11 14:27:15,091: [inspectIT] 6880   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/432430300
2015-08-11 14:27:15,094: [inspectIT] 6883   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/846974653
2015-08-11 14:27:15,099: [inspectIT] 6888   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1816756435
2015-08-11 14:27:15,102: [inspectIT] 6891   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1830190936
2015-08-11 14:27:15,106: [inspectIT] 6895   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/209429254
2015-08-11 14:27:15,109: [inspectIT] 6898   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/967576586
2015-08-11 14:27:15,113: [inspectIT] 6902   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1003693033
2015-08-11 14:27:15,116: [inspectIT] 6905   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/26757919
2015-08-11 14:27:15,120: [inspectIT] 6909   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/460702435
2015-08-11 14:27:15,123: [inspectIT] 6912   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/525575644
2015-08-11 14:27:15,127: [inspectIT] 6916   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1094674892
2015-08-11 14:27:15,130: [inspectIT] 6919   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/2119992687
2015-08-11 14:27:15,133: [inspectIT] 6922   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/315805187
2015-08-11 14:27:15,137: [inspectIT] 6926   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/2101636817
2015-08-11 14:27:15,140: [inspectIT] 6929   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/199657303
2015-08-11 14:27:15,143: [inspectIT] 6932   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/519979933
2015-08-11 14:27:15,146: [inspectIT] 6935   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/776484396
2015-08-11 14:27:15,150: [inspectIT] 6939   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1186339926
2015-08-11 14:27:15,153: [inspectIT] 6942   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1209770703
2015-08-11 14:27:15,156: [inspectIT] 6945   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/3540494
2015-08-11 14:27:15,160: [inspectIT] 6949   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1530295320
2015-08-11 14:27:15,163: [inspectIT] 6952   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/360936478
2015-08-11 14:27:15,166: [inspectIT] 6955   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/57241990
2015-08-11 14:27:15,170: [inspectIT] 6959   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/919446210
2015-08-11 14:27:15,173: [inspectIT] 6962   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1181815135
2015-08-11 14:27:15,177: [inspectIT] 6966   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/917768476
2015-08-11 14:27:15,180: [inspectIT] 6969   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/225909961
2015-08-11 14:27:15,183: [inspectIT] 6972   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1593165620
2015-08-11 14:27:15,187: [inspectIT] 6976   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/384617262
2015-08-11 14:27:15,190: [inspectIT] 6979   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1574749319
2015-08-11 14:27:15,193: [inspectIT] 6982   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/400064818
2015-08-11 14:27:15,197: [inspectIT] 6986   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/2694936
2015-08-11 14:27:15,200: [inspectIT] 6989   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$BMH/1808009213
2015-08-11 14:27:15,203: [inspectIT] 6992   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1866768727
2015-08-11 14:27:15,206: [inspectIT] 6995   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/895766599
2015-08-11 14:27:15,210: [inspectIT] 6999   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/404648734
2015-08-11 14:27:15,213: [inspectIT] 7002   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/2108297149
2015-08-11 14:27:15,217: [inspectIT] 7006   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/916835004
2015-08-11 14:27:15,220: [inspectIT] 7009   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1943634922
2015-08-11 14:27:15,224: [inspectIT] 7013   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1364497552
2015-08-11 14:27:15,227: [inspectIT] 7016   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/2032326802
2015-08-11 14:27:15,231: [inspectIT] 7020   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1777443462
2015-08-11 14:27:15,234: [inspectIT] 7023   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/914942811
2015-08-11 14:27:15,238: [inspectIT] 7027   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1611373863
2015-08-11 14:27:15,242: [inspectIT] 7031   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/182670350
2015-08-11 14:27:15,245: [inspectIT] 7034   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/833474933
2015-08-11 14:27:15,249: [inspectIT] 7038   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/195801026
2015-08-11 14:27:15,252: [inspectIT] 7041   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1939022383
2015-08-11 14:27:15,256: [inspectIT] 7045   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/507819576
2015-08-11 14:27:15,260: [inspectIT] 7049   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/945834881
2015-08-11 14:27:15,263: [inspectIT] 7052   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/157168588
2015-08-11 14:27:15,267: [inspectIT] 7056   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$MH/1154821602
2015-08-11 14:27:15,271: [inspectIT] 7060   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/100929741
2015-08-11 14:27:15,274: [inspectIT] 7063   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1321203216
2015-08-11 14:27:15,278: [inspectIT] 7067   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1111613684
2015-08-11 14:27:15,282: [inspectIT] 7071   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1260467793
2015-08-11 14:27:15,285: [inspectIT] 7074   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.LambdaForm$DMH/1360215046
2015-08-11 14:27:15,601: [inspectIT] 7390   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.BoundMethodHandle$Species_L4
2015-08-11 14:27:15,605: [inspectIT] 7394   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.BoundMethodHandle$Species_L3
2015-08-11 14:27:15,610: [inspectIT] 7399   [           main] ERROR analyzer.impl.ByteCodeAnalyzer - Error occurred instrumenting the byte code of class java.lang.invoke.BoundMethodHandle$Species_LL

Connecting the client to the CMR doesn't work either. Sounds logical to me.

**Comment by stefansiegl** [comment]
Sorry that you were running into the next problem. We have a ticket for your problem already open and  fixed but not integrated yet (https://inspectit-performance.atlassian.net/browse/INSPECTIT-1965)

You could easily apply the patch yourself. Find the file Agent/config/common/exclude-classes.cfg and change "exclude class java.lang.invoke.LambdaForm*" to "exclude-class java.lang.invoke.LambdaForm*"

**Comment by stefansiegl** [comment]
I created a ticket for the improvement of the Docker Images and the clarification of the documentation at https://inspectit-performance.atlassian.net/browse/INSPECTIT-1966

**Comment by ivansenic** [comment]
@cbonami As @stefansiegl suggested you can easily ignore labmda's with exclude-class fix.. However, this is not in fact an error as inspectIT has no support yet for lambda class.. Also sometimes some classes can not be instrumented, but it will not affect the running JVM..

To sum up, your application can run with no problems regardless of the _ByteCodeAnalyzer_ error messages..

**Comment by cbonami** [comment]
Ok, that's great.
Then I'll wait until the main issue is solved.

**Comment by stefansiegl** [comment]
@cbonami As the original issue described in this issue is addressed, I close this issue. You might want to watch the realization ticket, so you get updated as soon as the ticket is fixed. Once again thanks for bringing up the topic.

**Comment by cbonami** [comment]
Sorry, but I still cannot connect to the CMR.
And the two tickets that (1965, 1966) that you mentioned here above, don't deal with the problem.
So I don't understand why you close this issue .

**Comment by stefansiegl** [comment]
Oh, I am sorry. Did you check what @ivansenic suggested? The agent should connect even with these exceptions. Can you provide the log output of the cmr after starting the agent (this one should not contain the error anymore and show if the agent connected)

**Comment by cbonami** [comment]
It is fairly simple. I installed the CMR via docker, on my local dockerhost. Then I installed the UI (OSX version). Then I try to connect the UI to the CMR. No agents involved so far. Connection from UI to CMR fails immediately. Running a Java app with an agent doesn't work either.
You have all the logs you need, imo.

I tried to make a movie (screenflow) to show you the problem. So I decided to start from a clean slate. I removed (docker rmi) the CMR image and started a reinstall; when executing the command to run the CMR, I received this:

McBonami:~ bonami$ docker run -d --name inspectIT-CMR -p 8182:8182 -p 9070:9070 inspectit/cmr
Unable to find image 'inspectit/cmr:latest' locally
Pulling repository inspectit/cmr
Get https://index.docker.io/v1/repositories/inspectit/cmr/images: dial tcp: lookup index.docker.io on 192.168.101.119:53: read udp 192.168.101.119:53: i/o timeout

/sigh

**Comment by ivansenic** [comment]
@cbonami I understood that the connection problems appear with connecting agent to the CMR, so my bad.. Try connecting with the User Interface in the 1.6.2.65 version as well. For Mac the version is here: ftp://ntftp.novatec-gmbh.de/inspectit/releases/RELEASE.1.6.2.65/inspectit-macosx.cocoa.x86_64.zip.. All components involved in the communication must be in same version.. 

Can you please confirm that you can connect if UI is also in the v.1.6.2.65?

**Comment by ivansenic** [comment]
@cbonami Regarding the Docker issue, this is related to Docker itself.. Please see: http://stackoverflow.com/questions/28884488/cannot-download-docker-image-from-repository

**Comment by cbonami** [comment]
Ok, that solved it. Everything is in same version now.
You can close this.
